### ISSUE TITLE
Many Crashes

### ISSUE THREAD

**Issue by landry314** [etahamad/cts-fix#3]
Since installing version 2.4 I have been experiencing many system crashes on my phone at all sorts of times. I can't say how or even that it is related but it is correlated. Anyone else having issues?

Using LineageOS 20 on Pixel 5 with Magisk 25.2

**Comment by etahamad** [comment]
This is a source edition repo.
Kindly refer to this repo https://github.com/Displax/safetynet-fix/releases/
Download this model
Remove the old one
Install the one you downloaded

**Comment by etahamad** [comment]
Fixed
